apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: nginx
      version: "15.9.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values: {}
